# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: johanmalasquez
type: Opaque
data:
  # Credenciales de la base de datos y RapidAPI en Base64
  DATABASE_URL: "cjJkYmM6cG9zdGdyZXNxbDovL2VwLXN0aWxsLXVuaW9uLWE0eHBvamt5LXBvb2xlci51cy1lYXN0LTEuYXdzLm5lb24udGVjaC9jYm90P3NzbD10cnVl"
  DATABASE_USERNAME: "Y2JvdF9vd25lcg=="
  DATABASE_PASSWORD: "bnBnX3NmQml5bndEaEYwNg=="
  RAPIDAPI_URL: "aHR0cHM6Ly9vcGVuLWFpMjEucC5yYXBpZGFwaS5jb20vY29udmVyc2F0aW9ubGxhbWE="
  RAPIDAPI_HOST: "b3Blbi1haTIxLnAucmFwaWRhcGkuY29t"
  RAPIDAPI_APIKEY: "MzQ2MDQzM2JmMW1zaGE0YTFhOWIzN2Q0NzljOHAxN2UxN2Jqc25hZTc4ODU1NTQwNmY="

# echo -n "my-user" | base64
# echo -n "my-password" | base64
# echo "bXktdXNlcg==" | base64 --decode